resolver: lts-11.2
packages:

nix:
  enable: true
  shell-file: shell.nix
  #packages: [llvm_6, zlib, libedit, ncurses,binutils]

#extra-deps:
#- llvm-hs-6.0.0
#- llvm-hs-pure-6.0.0
#flags:
# llvm-hs:
#   shared-llvm: true

